import './globals.css'
import {Inter} from 'next/font/google'
import StyledComponentsRegistry from './styledComponent';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.min.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
    <head>
      <title>쇼핑위키</title>
    </head>
    <body style={{backgroundColor: "#1e272e"}} className={inter.className}>
    <StyledComponentsRegistry>
      {children}
    </StyledComponentsRegistry>
    </body>
    </html>
  )
}
